### PR TITLE
add readMe

### PR DESCRIPTION
**Pull request by blaquebeardcoder**
Oh... so I leave some comments about this request here.

### CODE REVIEW

**Comment by blaquebeardcoder** [comment]
This is a sample comment-- not sure where this will show up. Who reads this?

**Review by shafeeshafee — COMMENTED** [review]
Looks great, Jahaziel.

**Review by shafeeshafee — APPROVED** [review]
Approved.

**Review by blaquebeardcoder — COMMENTED** [review]
This looks **great**-- sample comment.

**Pull request merged**
